# Labels for keeping the merge button red
- name: On Call Review needed
  color: "AD1C21"
  description: "This work needs an on-call review"

# Labels to affirm the merge button can be green
- name: On Call Review complete
  color: "1FC058"
  description: "On call review complete"

# Labels for tracking statistics and history
- name: MVP
  color: f5f7f9
  description: "A Minimum Viable Product example to show the bare bones of how to use a service via an SDK."
- name: Workflow
  color: f5f7f9
  description: "A simple code example to show how certain tasks can be accomplished using several services and SDKs."
- name: Application
  color: f5f7f9
  description: "An example with multiple AWS Services and SDKs to show how to build a complete, working application."
- name: Task
  color: f5f7f9
  description: "A general update to the code base for language clarification, missing actions, tests, etc."
- name: Bug
  color: f5f7f9
  description: "An update to fix incorrect code or typos."

# Labels for general which aren't tracked
- name: Scout
  color: f5f7f9
  description: "An example which other languages will use for reference later on."
- name: Follow
  color: f5f7f9
  description: "After Scouts, more languages are added to examples as Follows."

- name: C++
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for C++"
- name: DotNet-v3
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for .NET V3"
- name: Go-v1
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Go V1"
- name: Go-v2
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Go V2"
- name: Java-v1
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Java V1"
- name: Java-v2
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Java V2"
- name: Javascript-v2
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Javascript V2"
- name: Javascript-v3
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Javascript V3"
- name: Kotlin
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Kotlin"
- name: PHP
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for PHP"
- name: Python
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Python (boto3)"
- name: Ruby
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Ruby"
- name: Rust
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Rust (Preview)"
- name: "SAP ABAP"
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for SAP ABAP"
- name: Swift
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Swift"
- name: Typescript
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Typescript"
- name: Shell
  color: "f5f7f9"
  description: "Tools written in bash/sh"
- name: Tools
  color: "f5f7f9"
  description: "This issue relates to a custom tooling to streamline development tasks"
- name: CLI
  description: "Relates to the AWS CLI"
  color: "f5f7f9"
- name: CDK
  color: "f5f7f9"
  description: "Relates to the AWS Cloud Development Kit (CDK)"
- name: CloudFormation
  description: "Relates to CloudFormation templates"
  color: "f5f7f9"
- name: GitHub settings
  color: "f5f7f9"
  description: "This affects GitHub settings"

# Labels to visually distinguish special types of issues
- name: Urgent
  color: "00FFFF"
  description: "Very important and needs attention"
- name: Epic
  color: "d8bfd8"
  description: "Contains many smaller pieces to work on separately"
- name: Tracker
  color: "a0d0fa"
  description: "Similar to an Epic, but used to track a single individual's multi-part issues."
- name: Internal
  color: "f2bb22"
  description: "To help track internal tickets in a single location."

# DEPRECATED labels
# Text review labels - now optional, kept for history
- name: Text Review complete
  color: "f5f7f9"
  description: "Text review complete"
- name: Text Review needed
  color: "f5f7f9"
  description: "This work needs editorial (text) review"
- name: Text Review not needed
  color: "f5f7f9"
  description: "This contains no text which needs review"

