- name: lang/all-languages
  color: "663399"
  description: "This issue relates to all AWS SDKs"
- name: lang/cpp
  color: "663399"
  description: "This issue relates to the AWS SDK for C++"
- name: lang/dotnet-v3
  color: "663399"
  description: "This issue relates to the AWS SDK for .NET V3"
- name: lang/go-v1
  color: "663399"
  description: "This issue relates to the AWS SDK for Go V1"
- name: lang/go-v2
  color: "663399"
  description: "This issue relates to the AWS SDK for Go V2"
- name: lang/java-v1
  color: "663399"
  description: "This issue relates to the AWS SDK for Java V1"
- name: lang/java-v2
  color: "663399"
  description: "This issue relates to the AWS SDK for Java V2"
- name: lang/javascript-v2
  color: "663399"
  description: "This issue relates to the AWS SDK for Javascript V2"
- name: lang/javascript-v3
  color: "663399"
  description: "This issue relates to the AWS SDK for Javascript V3"
- name: lang/kotlin
  color: "663399"
  description: "This issue relates to the AWS SDK for Kotlin"
- name: lang/php
  color: "663399"
  description: "This issue relates to the AWS SDK for PHP"
- name: lang/python
  color: "663399"
  description: "This issue relates to the AWS SDK for Python (boto3)"
- name: lang/ruby
  color: "663399"
  description: "This issue relates to the AWS SDK for Ruby"
- name: lang/rust
  color: "663399"
  description: "This issue relates to the AWS SDK for Rust (Preview)"
- name: lang/swift
  color: "663399"
  description: "This issue relates to the AWS SDK for Swift"
- name: lang/typescript
  color: "663399"
  description: "This issue relates to the AWS SDK for Typescript"
- name: lang/shell
  color: "663399"
  description: "Tools written in bash/sh"
- name: tool/cli
  description: "Relates to the AWS CLI"
  color: "663399"
- name: tool/cdk
  color: "663399"
  description: "Relates to the AWS Cloud Development Kit (CDK)"
- name: tool/cloudformation
  description: "Relates to CloudFormation templates"
  color: "663399"
- name: tool/integration-testing
  description: "Relates to integration testing"
  color: "663399"
- name: status/on-call-review-needed
  color: "AD1C21"
  description: "This work needs an on-call review"
- name: status/on-call-review-complete
  color: "1FC058"
  description: "Code review complete"
- name: status/text-review-needed
  color: "AD1C21"
  description: "This work needs editorial (text) review"
- name: status/text-review-complete
  color: "1FC058"
  description: "Text review complete"
- name: status/no-text-review-needed
  color: "5E2824"
  description: "No text which needs review"
- name: status/ready-to-merge
  color: "7FFF00"
  description: "This work is READY TO MERGE"
- name: status/in-progress
  color: "008080"
  description: "This work is currently in progress"
- name: status/back-to-author
  color: "00FFFF"
  description: "This work needs further work (other)"
- name: status/needs-input
  color: "00FFFF"
  description: "This work needs input from the reporter"
- name: research-spike
  color: "00FFFF"
  description: "This work needs research by the resolver"
- name: status/on-hold
  color: "000000"
  description: "On Hold. Do not merge until released by author."
- name: status/future-release
  color: "000000"
  description: "Hold for merge until after release"
- name: status/stale
  color: "00FFFF"
  description: "This is stale"
- name: type/bug
  color: "d8bfd8"
  description: "A bug in an existing code sample"
- name: type/internal
  color: "000000"
  description: "A PR linking to an internal issue"
- name: size/epic
  color: "d8bfd8"
  description: "Contains many smaller pieces to work on separately"
- name: type/github-settings
  color: "5AF8F9"
  description: "This affects GitHub settings"
- name: urgent
  color: "FF0000"
  description: "Very important and needs attention"
- name: size/small
  color: "e9ecef"
  description: "A small amount of effort/complexity"
- name: size/medium
  color: "ced4da"
  description: "A medium amount of effort/complexity"
- name: size/large
  color: "adb5bd"
  description: "A large amount of effort/complexity"
- name: cross-service-team
  color: "e0cdff"
  description: "PRs for the Cross Service Cloud Sherpas"
- name: type/tracking
  color: "5aa9f9"
  description: "Similar to an Epic, but used to track a single individual's multi-part issues."
