[package]
name = "globalaccelerator-code-examples"
version = "0.1.0"
authors = ["Akshat Aranya <aranyaa@amazon.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { version = "1.0.1", features = ["behavior-version-latest"] }
aws-sdk-globalaccelerator = { version = "1.3.0" }
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = "0.1.8"
clap = { version = "4.4", features = ["derive"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
