[package]
name = "kms-code-examples"
version = "0.1.0"
authors = [
  "Russell Cohen <rcoh@amazon.com>",
  "Doug Schwartz <dougsch@amazon.com",
]
edition = "2021"
description = "Example usage of the KMS service"

[dependencies]
aws-config = { version = "1.0.1", features = ["behavior-version-latest"] }
aws-sdk-kms = { version = "1.3.0" }
tokio = { version = "1.20.1", features = ["full"] }
base64 = "0.13.0"
clap = { version = "4.4", features = ["derive"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
