[package]
name = "custom-retries-examples"
version = "0.1.0"
authors = [
  "John DiSanti <jdisanti@amazon.com>",
  "Doug Schwartz <dougsch@amazon.com>",
  "David Souther <dpsouth@amazon.com>"
]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { version = "1.0.1", features = ["behavior-version-latest"] }
aws-credential-types = { version = "1.0.1" }
aws-sdk-s3 = { version = "1.4.0" }
tokio = { version = "1.20.1", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
lazy_static = "1.4.0"
async_once = "0.2.6"
tracing = "0.1.37"
