[package]
name = "dynamodb-code-examples"
version = "0.1.0"
authors = [
  "Russell Cohen <rcoh@amazon.com>",
  "Doug Schwartz <dougsch@amazon.com>",
  "David Souther <davidsouther@gmail.com>"
]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { version = "1.0.1", features = ["behavior-version-latest"] }
aws-http = { version = "0.60.0" }
aws-sdk-dynamodb = { version = "1.3.0" }
aws-smithy-runtime = { version = "1.0.1", features = ["test-util"] }
aws-smithy-types = { version = "1.0.1" }
axum = "0.5.16"
clap = { version = "4.4", features = ["derive"] }
futures = "0.3"
http = "0.2.5"
log = "0.4.17"
rand = "0.8.3"
sdk-examples-test-utils = { path = "../../test-utils" }
serde = {version = "1.0", features = ["derive"]}
serde_dynamo = { version = "4", features = ["aws-sdk-dynamodb+0_22"] }
serde_json = "1"
thiserror = "1.0"
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = "0.1.8"
tower-http = { version = "0.3.0", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
