/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// snippet-start:[javascript.v3.wkflw.topicsandqueues.logger]
export class Logger {
  /**
   * @param {string} message
   */
  log(message) {
    console.log(message);
    return Promise.resolve();
  }
}

export class SlowLogger extends Logger {
  constructor(delay) {
    super();
    this.delay = delay;
  }

  sleep() {
    return new Promise((resolve) => setTimeout(resolve, this.delay));
  }

  /**
   * @param {string} message
   */
  async logSlow(message) {
    const chars = message.split("");
    for (const c of chars) {
      process.stdout.write(c);
      await this.sleep();
    }
    process.stderr.write("\n");
  }

  /**
   * Write a message to the console. Split the message into multiple lines if
   * a line would be longer than the max width. Do not split in the middle of
   * a word.
   * - Generated by CodeWhisperer.
   * @param {string} message
   * @param {number} maxWidth
   */
  async log(message, maxWidth = 80) {
    const words = message.split(" ");
    let line = "";
    for (const word of words) {
      if (line.length + word.length > maxWidth) {
        await this.logSlow(line);
        line = "";
      }
      line += word + " ";
    }
    await this.logSlow(line);
  }
}
// snippet-end:[javascript.v3.wkflw.topicsandqueues.logger]
