name: Feature request
description: Request a new code example
title: "[Enhancement]: <DESCRIPTIVE TITLE HERE>"
labels: ["type/enhancement"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Warning
        Issues that don't use the following template will be marked `status/back-to-author` and assigned back to the creator.
        
        ---
        
        # ✨ Code example details
  - type: textarea
    id: context
    attributes:
      label: Background story
      description: Take a moment and give us some context. Why is this example important to you?
      placeholder: Be specific. Ctrl+Copy screenshots.
    validations:
      required: true
  - type: textarea
    id: accomplishment
    attributes:
      label: What does this example accomplish?
      description: Provide a clear and brief description of what the code example should do. For example, "I want to upload a file to the cloud."
      placeholder: Be specific. Ctrl+Copy screenshots.
    validations:
      required: true
  - type: input
    id: which-services
    attributes:
      label: Which AWS service(s)?
      description: List the [AWS services](https://aws.amazon.com/products/) that this code will engage.
      placeholder: Be specific.
    validations:
      required: true
  - type: checkboxes
    id: lingo-type
    attributes:
      label: Which AWS SDKs or tools?
      options:
        - label: All languages
        - label: .NET
        - label: Go (v2)
        - label: Java
        - label: Java (v2)
        - label: JavaScript
        - label: JavaScript (v3)
        - label: Kotlin
        - label: PHP
        - label: Python
        - label: Ruby
        - label: Rust
        - label: Swift
        - label: Not applicable
  - type: textarea
    id: which-examples
    attributes:
      label: Are there existing code examples to leverage?
      description: Are there any [existing code examples](https://docs.aws.amazon.com/code-library/latest/ug/what-is-code-library.html) that might provide a foundation?
      placeholder: Use hyperlinks.
    validations:
      required: false
  - type: textarea
    id: your-code
    attributes:
      label: Do you have any reference code?
      description: This will be automatically formatted into code. No backticks required.
      render: shell
  - type: markdown
    attributes:
      value: |
        ---
        
        ## What's next?
        A member of the AWS SDK Example Code team will review your issue and reply within 10 business days. 🙂
