[package]
name = "sitewise-code-examples"
version = "0.1.0"
authors = ["Lawrence Xiao <delonx@amazon.com>"]
edition = "2021"

# For more keys and their definitions, see https://doc.rust-lang.org/cargo/reference/manifest.html.

[dependencies]
aws-config = { version = "1.0.1", features = ["behavior-version-latest"] }
aws-sdk-iotsitewise = { version = "1.3.0" }
aws-smithy-types-convert = { version = "0.60.0", features = [
  "convert-chrono",
] }
clap = { version = "4.4", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.20.1", features = ["full"] } 
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
