Parameters:
  VPCId:
    Type: AWS::EC2::VPC::Id
    # aws ec2 describe-vpcs --filters Name=is-default,Values=true --query "Vpcs[0].VpcId" # "vpc-1234567890abcdef"
  SGId:
    Type: String
    # aws ec2 describe-security-groups --group-names default --query "SecurityGroups[0].GroupId"
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    # aws ec2 describe-subnets --filters Name=vpc-id,Values="vpc-01234567890abcdef" --query "Subnets[].SubnetId" # "subnet-01234567890abcdef", "subnet-abcdef0123456789"
  InstanceType:
    Type: String
    Default: t3.medium
  ExternalCidr:
    Type: String
    Default: "0.0.0.0/0"
  SSMFailure:
    Type: String
    Default: "empty" # 'static' for static response, any other string for empty response
  SSMHealthCheck:
    Type: String
    Default: "shallow" # 'deep' to perform health checks on downstream resources
  SSMTableName:
    Type: String
    Default: ""
  LaunchTemplateVersion:
    Type: String
    Default: "1.0.0"

Conditions:
  EmptySSMTableName: !Equals ["", !Ref SSMTableName]

Resources:
  # 1. A DynamoDB table that acts as a service that recommends books, movies, and songs.
  DocExampleRecommendationServiceTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: doc-example-recommendation-service
      AttributeDefinitions:
        - AttributeName: MediaType
          AttributeType: S
        - AttributeName: ItemId
          AttributeType: N
      KeySchema:
        - AttributeName: MediaType
          KeyType: HASH
        - AttributeName: ItemId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # 1b. A Lambda function that initializes data in the Database
  DocExampleRecommendationServiceInitializerFn:
    Type: AWS::Lambda::Function
    DependsOn: DocExampleRecommendationServiceTable
    Properties:
      Runtime: nodejs20.x
      Handler: index.handler
      Timeout: 30
      Role: !GetAtt DocExampleRecommendationServiceInitializerFnExecutionRole.Arn
      Environment:
        Variables:
          tableName: !Ref DocExampleRecommendationServiceTable
      Code:
        ZipFile: |
          const { DynamoDBClient, PutItemCommand } = require("@aws-sdk/client-dynamodb");
          const response = require("cfn-response");

          const client = new DynamoDBClient({});
          const tableName = process.env.tableName;

          exports.handler = async (event, context) => {
            console.log("REQUEST RECEIVED", {tableName}, event);

            if (event.RequestType !== "Create") {
              await response.send(event, context, response.SUCCESS, {});
              return;
            }

            const recommendations = [
              {"MediaType": {"S": "Book"}, "ItemId":{"N": "1"}, "Title": {"S": "Pride and Prejudice"}, "Creator": {"S": "Jane Austen"}},
              {"MediaType": {"S": "Book"}, "ItemId": {"N": "2"}, "Title": {"S": "The Lord of the Rings"}, "Creator": {"S": "J. R. R. Tolkien"}},
              {"MediaType": {"S": "Book"}, "ItemId": {"N": "3"}, "Title": {"S": "The Three Musketeers"}, "Creator": {"S": "Alexandre Dumas"}},
              {"MediaType": {"S": "Movie"}, "ItemId": {"N": "1"}, "Title": {"S": "Delicatessen"}, "Creator": {"S": "Jeunet et Caro"}},
              {"MediaType": {"S": "Movie"}, "ItemId": {"N": "2"}, "Title": {"S": "The Princess Bride"}, "Creator": {"S": "Rob Reiner"}},
              {"MediaType": {"S": "Movie"}, "ItemId": {"N": "3"}, "Title": {"S": "12 Angry Men"}, "Creator": {"S": "Sidney Lumet"}},
              {"MediaType": {"S": "Song"}, "ItemId": {"N": "1"}, "Title": {"S": "And Dream of Sheep"}, "Creator": {"S": "Kate Bush"}},
              {"MediaType": {"S": "Song"}, "ItemId": {"N": "2"}, "Title": {"S": "Mirrorball"}, "Creator": {"S": "Elbow"}},
              {"MediaType": {"S": "Song"}, "ItemId": {"N": "3"}, "Title": {"S": "Guardians of Asgaard"}, "Creator": {"S": "Amon Amarth"}}
            ];

            try {
              await Promise.all(recommendations.map(recommendation => 
                client.send(new PutItemCommand({TableName: tableName, Item: recommendation}))
              ));
              console.log("PUT ITEMS SUCCESS", {tableName});
              await response.send(event, context, response.SUCCESS, {});
            } catch (e) {
              console.log("PUT ITEMS ERROR", {tableName}, {e});
              await response.send(event, context, response.ERROR, {e});
            }
          };

  DocExampleRecommendationServiceInitializerFnExecutionRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"

  # 1c. A CustomResource to trigger the Lambda
  DocExampleRecommendationServiceInitializer:
    Type: Custom::DocExampleRecommendationServiceInitializer
    Properties:
      ServiceToken: !GetAtt DocExampleRecommendationServiceInitializerFn.Arn

  # 2. An instance profile and an associated role and policy that grants permission to instances to access DynamoDB and Systems Manager.
  DocExampleRecommendationServiceInstanceProfileRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      RoleName: doc-example-resilience-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: "sts:AssumeRole"

  DocExampleRecommendationServiceInstanceProfilePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: doc-example-resilience-pol
      Roles:
        - !Ref DocExampleRecommendationServiceInstanceProfileRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "dynamodb:BatchGetItem"
              - "dynamodb:Describe*"
              - "dynamodb:GetItem"
              - "dynamodb:List*"
              - "dynamodb:Query"
              - "dynamodb:Scan"
            Resource:
              - !GetAtt DocExampleRecommendationServiceTable.Arn
          - Effect: Allow
            Action:
              - "ssm:GetParameters"
            Resource:
              - "arn:aws:ssm:*"

  DocExampleRecommendationServiceInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: doc-example-resilience-prof
      Roles:
        - !Ref DocExampleRecommendationServiceInstanceProfileRole

  # 3. A launch template that specifies the instance profile and a startup script that starts a Python web server on each instance.
  DocExampleRecommendationServiceKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: doc-example-resilience-key

  DocExampleRecommendationServiceDebugSecurityGroupSSHIngress:
    # Add self traffic for ingress, without creating a circular dependency
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SGId
      CidrIp: !Ref ExternalCidr
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22

  DocExampleRecommendationServiceDebugSecurityGroupHTTPIngress:
    # Add self traffic for ingress, without creating a circular dependency
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SGId
      CidrIp: !Ref ExternalCidr
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80

  DocExampleRecommendationServiceLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: doc-example-resilience-template
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
            - Key: InternalVersion
              Value: !Ref LaunchTemplateVersion # Increment this value & update the stack to trigger a rolling update of the group
      LaunchTemplateData:
        InstanceType: !Ref InstanceType
        ImageId: resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
        IamInstanceProfile:
          Name: !Ref DocExampleRecommendationServiceInstanceProfile
        KeyName: !Ref DocExampleRecommendationServiceKeyPair
        # SecurityGroupIds:
        #   - !Ref DocExampleRecommendationServiceDebugSecurityGroup
        MetadataOptions:
          HttpTokens: required
        UserData: !Base64 |
          #!/bin/bash
          yum -y update
          sleep 30 # prevent "Error: Rpmdb changed underneath us"
          yum install python-pip -y
          python3 -m pip install boto3 ec2-metadata
          wget -O server.py https://raw.githubusercontent.com/awsdocs/aws-doc-sdk-examples/main/scenarios/features/resilient_service/resources/server.py
          python3 server.py 80

  # 4. An Auto Scaling group that starts EC2 instances, one in each of three Availability Zones.
  DocExampleRecommendationServiceAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: 2
        MinInstancesInService: 1
    Properties:
      AutoScalingGroupName: doc-example-resilience-group
      AvailabilityZones: { "Fn::GetAZs": { "Ref": "AWS::Region" } }
      LaunchTemplate:
        LaunchTemplateId: !Ref DocExampleRecommendationServiceLaunchTemplate
        Version: !GetAtt DocExampleRecommendationServiceLaunchTemplate.LatestVersionNumber
      TargetGroupARNs:
        - !Ref DocExampleRecommendationServiceTargetGroup
      MinSize: 3
      MaxSize: 3

  # 6. A target group that connects the load balancer to instances in the Auto Scaling group.
  DocExampleRecommendationServiceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: doc-example-resilience-tg
      Protocol: HTTP
      Port: 80
      HealthCheckPath: /healthcheck
      HealthCheckIntervalSeconds: 10
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      VpcId: !Ref VPCId

  # 5. An Application Load Balancer that handles HTTP requests to a single endpoint.
  DocExampleRecommendationServiceLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: doc-example-resilience-lb
      Subnets: !Ref Subnets

  # 7. A listener that is added to the load balancer and forwards requests to the target group.
  DocExampleRecommendationServiceListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref DocExampleRecommendationServiceLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DocExampleRecommendationServiceTargetGroup

  DocExampleRecommendationServiceParameterTable:
    Type: AWS::SSM::Parameter
    Properties:
      Name: doc-example-resilient-architecture-table
      Type: String
      Value:
        !If [
          "EmptySSMTableName",
          !Ref DocExampleRecommendationServiceTable,
          !Ref SSMTableName,
        ]

  # aws ssm put-parameter --name doc-example-resilient-architecture-health-check --value static --overwrite
  DocExampleRecommendationServiceParameterFailure:
    Type: AWS::SSM::Parameter
    Properties:
      Name: doc-example-resilient-architecture-failure-response
      Type: String
      Value: !Ref SSMFailure

  # aws ssm put-parameter --name doc-example-resilient-architecture-health-check --value deep --overwrite
  DocExampleRecommendationServiceParameterHealthCheck:
    Type: AWS::SSM::Parameter
    Properties:
      Name: doc-example-resilient-architecture-health-check
      Type: String
      Value: !Ref SSMHealthCheck

Outputs:
  LB:
    # aws cloudformation describe-stacks --stack-name resilience-demo --query 'Stacks[0].Outputs[?OutputKey==`LB`].OutputValue | [0]' # "doc-example-resilience-lb-0123456789.us-east-1.elb.amazonaws.com"
    Value: !GetAtt DocExampleRecommendationServiceLoadBalancer.DNSName
  Key:
    # aws cloudformation describe-stacks --stack-name resilience-demo --query 'Stacks[0].Outputs[?OutputKey==`Key`].OutputValue | [0]' # "key-0123456789"
    # aws ssm get-parameter --name /ec2/keypair/key-0123456789 --with-decryption --query Parameter.Value --output text > doc-example-resilience-key.pem
    # chmod 400 doc-example-resilience-key.pem
    Value: !GetAtt DocExampleRecommendationServiceKeyPair.KeyPairId
  TGArn:
    # aws elbv2 describe-target-health --target-group-arn tg-0123456789
    Value: !Ref DocExampleRecommendationServiceTargetGroup
