Resources:
  RegularUser:
    Type: AWS::IAM::User
  ExpressUser:
    Type: AWS::IAM::User
  ExpressPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AllowExpressOperations
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - "s3express:CreateBucket"
              - "s3express:CreateSession"
              - "s3express:CopyObject"
              - "s3express:GetObject"
              - "s3express:PutObject"
              - "s3express:ListObjects"
              - "s3express:DeleteObjects"
              - "s3express:DeleteObject"
              - "s3express:DeleteBucket"
              - "s3:GetObject"
              - "s3:CopyObject"
            Resource: "*"
      Users:
        - !Ref ExpressUser
  RegularPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AllowRegularOperations
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - "s3:CreateBucket"
              - "s3:PutObject"
              - "s3:GetObject"
              - "S3:ListObjects"
              - "S3:DeleteObjects"
              - "S3:DeleteObject"
              - "s3:ListBucket"
              - "s3:DeleteBucket"
            Resource: "*"
      Users:
        - !Ref RegularUser
Outputs:
  RegularUser:
    Value: !Ref RegularUser
  ExpressUser:
    Value: !Ref ExpressUser
