# This AWS CloudFormation template creates the following AWS resources:
#
# * A table in Amazon DynamoDB.
#
# You can run this app instead of running equivalent AWS SDK for Ruby
# code examples elsewhere in this directory, such as:
#
# * dynamodb-ruby-example-create-users-table.rb
#
# You can run this template in a few different ways:
#
# 1. To run this template with the AWS Command Line Interface (AWS CLI):
#
#    aws cloudformation create-stack --template-body file://dynamodb-ruby-example-create-users-table.yaml --stack-name DynamodbRubyExampleCreateUsersTableStack
#
#    This will create a stack in AWS CloudFormation. This stack will create
#    the specified AWS resources.
#
#    To display the names of the generated resources, run the following command:
#
#    aws cloudformation describe-stacks --stack-name DynamodbRubyExampleCreateUsersTableStack --query Stacks[0].Outputs --output text
#
#    Note that the generated resources might not be immediately available.
#    You can keep running this command until their names are displayed.
#
# 2. To run this template with the AWS CloudFormation console, sign in at:
#
#    https://console.aws.amazon.com/cloudformation
#
#    Choose Create stack, and then follow
#    the on-screen instructions to create a stack in AWS CloudFormation
#    based on this template. This stack will create the specified AWS resources.
#
#    The names of the generated resources will display on the stack's
#    Outputs tab in the console after the stack's status displays as
#    CREATE_COMPLETE.
#
# This file was generated from an AWS Cloud Development Kit (AWS CDK) app at:
#
# https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/resources/cdk/dynamodb-ruby-example-create-users-table

Resources:
  table8235A42E:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: "N"
        - AttributeName: FirstName
          AttributeType: S
        - AttributeName: LastName
          AttributeType: S
        - AttributeName: AirMiles
          AttributeType: "N"
      GlobalSecondaryIndexes:
        - IndexName: LastNameFirstNameIndex
          KeySchema:
            - AttributeName: FirstName
              KeyType: HASH
            - AttributeName: LastName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 10
        - IndexName: AirMileageIndex
          KeySchema:
            - AttributeName: AirMiles
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 10
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 10
      TableName: Users
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: DynamodbRubyExampleCreateUsersTableStack/table/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.87.1,@aws-cdk/assets=1.87.1,@aws-cdk/aws-applicationautoscaling=1.87.1,@aws-cdk/aws-autoscaling-common=1.87.1,@aws-cdk/aws-cloudwatch=1.87.1,@aws-cdk/aws-codeguruprofiler=1.87.1,@aws-cdk/aws-dynamodb=1.87.1,@aws-cdk/aws-ec2=1.87.1,@aws-cdk/aws-ecr=1.87.1,@aws-cdk/aws-ecr-assets=1.87.1,@aws-cdk/aws-events=1.87.1,@aws-cdk/aws-iam=1.87.1,@aws-cdk/aws-kms=1.87.1,@aws-cdk/aws-lambda=1.87.1,@aws-cdk/aws-logs=1.87.1,@aws-cdk/aws-s3=1.87.1,@aws-cdk/aws-s3-assets=1.87.1,@aws-cdk/aws-sqs=1.87.1,@aws-cdk/aws-ssm=1.87.1,@aws-cdk/cloud-assembly-schema=1.87.1,@aws-cdk/core=1.87.1,@aws-cdk/custom-resources=1.87.1,@aws-cdk/cx-api=1.87.1,@aws-cdk/region-info=1.87.1,jsii-runtime=node.js/v15.3.0
    Metadata:
      aws:cdk:path: DynamodbRubyExampleCreateUsersTableStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  TableName:
    Value:
      Ref: table8235A42E
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

