# snippet-start:[logging.rust.logger-cargo.toml]
[package]
authors = [
  "Russell Cohen <rcoh@amazon.com>",
  "Doug Schwartz <dougsch@amazon.com>",
]
edition = "2021"
name = "logging-example"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { version = "1.0.1", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = { version = "1.3.0" }
# snippet-start:[logging.rust.logger-cargo.toml-env_logger]
env_logger = "0.9.0"
# snippet-end:[logging.rust.logger-cargo.toml-env_logger]
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.20.1", features = ["full"] }
# snippet-end:[logging.rust.logger-cargo.toml]
