---
# Amazon Simple Email Service (Amazon SES) examples.
files:
  - path: ses_email.py
    services:
      - ses
  - path: ses_generate_smtp_credentials.py
    services:
      - ses
  - path: ses_identities.py
    services:
      - ses
  - path: ses_receipt_handler.py
    services:
      - ses
  - path: ses_replicateidentities
    services:
      - ses
  - path: ses_replicate_identities.py
    services:
      - route53
      - ses
  - path: ses_templates.py
    services:
      - ses
  - path: test/conftest.py
    services:
      - ses
  - path: test/test_ses_email.py
    services:
      - ses
  - path: test/test_ses_identities.py
    services:
      - ses
  - path: test/test_ses_receipt_handler.py
    services:
      - ses
  - path: test/test_ses_replicate_identities.py
    services:
      - route53
      - ses
  - path: test/test_ses_templates.py
    services:
      - ses
...
