Resources:
  iotworkflowtopicEC6B5DCD:
    Type: AWS::SNS::Topic
    Metadata:
      aws:cdk:path: doc-example-iot-workflow-stack/iot-workflow-topic/Resource
  docexampleimportrole77AD6B59:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: iot.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: doc-example-iot-workflow-stack/doc-example-import-role/Resource
  docexampleimportroleDefaultPolicy627063D0:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: dynamodb:*
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: docexampleimportroleDefaultPolicy627063D0
      Roles:
        - Ref: docexampleimportrole77AD6B59
    Metadata:
      aws:cdk:path: doc-example-iot-workflow-stack/doc-example-import-role/DefaultPolicy/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02OQQ7CIBREz+IevuDCuO8BNNi9QcDkt5TfFNAYwt1t6cbVvHmZxZxACgHioD+RGztyj08o96TNyFb1KDFEKD3NaFj3Cg0qQz1BUeTd5lreyKP5bnWnWplykfJi2uaa05xTW//ZjoLFhBQqC2QdDPH4lheQ5/XPEBH5kkPCyYHa8wekm8DQrAAAAA==
    Metadata:
      aws:cdk:path: doc-example-iot-workflow-stack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  SNSTopicArn:
    Value:
      Ref: iotworkflowtopicEC6B5DCD
  RoleArn:
    Value:
      Fn::GetAtt:
        - docexampleimportrole77AD6B59
        - Arn
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

