Resources:
  GlueDataBucket278CFAC6:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: glue-2cf5649393c7465f926ae00d0592eba8
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: EntityResolutionCdkStack/GlueDataBucket/Resource
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId:
        Ref: AWS::AccountId
      DatabaseInput:
        Name: entity_resolution_db
    Metadata:
      aws:cdk:path: EntityResolutionCdkStack/GlueDatabase
  GlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId:
        Ref: AWS::AccountId
      DatabaseName:
        Ref: GlueDatabase
      TableInput:
        Name: entity_resolution
        StorageDescriptor:
          Columns:
            - Name: id
              Type: string
            - Name: name
              Type: string
            - Name: email
              Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location:
            Fn::Join:
              - ""
              - - s3://
                - Ref: GlueDataBucket278CFAC6
                - /data/
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters:
              serialization.format: "1"
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
        TableType: EXTERNAL_TABLE
    DependsOn:
      - GlueDatabase
    Metadata:
      aws:cdk:path: EntityResolutionCdkStack/GlueTable
  EntityResolutionRoleB51A51D3:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: entityresolution.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonS3FullAccess
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AWSEntityResolutionConsoleFullAccess
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AWSGlueConsoleFullAccess
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSGlueServiceRole
    Metadata:
      aws:cdk:path: EntityResolutionCdkStack/EntityResolutionRole/Resource
  EntityResolutionRoleDefaultPolicy586C8066:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - entityresolution:GetMatchingWorkflow
              - entityresolution:StartMatchingWorkflow
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: EntityResolutionRoleDefaultPolicy586C8066
      Roles:
        - Ref: EntityResolutionRoleB51A51D3
    Metadata:
      aws:cdk:path: EntityResolutionCdkStack/EntityResolutionRole/DefaultPolicy/Resource
  OutputBucket7114EB27:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: entity-resolution-output-entityresolutioncdkstack
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: EntityResolutionCdkStack/OutputBucket/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02MMQ+CMBSEfwt7eYLEuFsnFwy6m0cp5klpDW0lpul/N7SL0919d7k91M0BqgJXW4phKhX1EG4OxcRwtY9gGwgnLybpGB91dpE9lZcQ+KjP6LBHK7fyjr2SkRHOEDqjEkt6NYrEd4vZxcg6aY1fRNq03r19uv+n3OiBHBkd2QU/uKuPUEHdFC9LVC5eO5oldFl/L3LHkcUAAAA=
    Metadata:
      aws:cdk:path: EntityResolutionCdkStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  EntityResolutionArn:
    Description: The ARN of the Glue Role
    Value:
      Fn::GetAtt:
        - EntityResolutionRoleB51A51D3
        - Arn
  GlueTableArn:
    Description: The ARN of the Glue Table
    Value:
      Fn::Join:
        - ""
        - - "arn:aws:glue:"
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - :table/
          - Ref: GlueDatabase
          - /entity_resolution
  GlueDataBucketName:
    Description: The name of the Glue Data Bucket
    Value:
      Ref: GlueDataBucket278CFAC6
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - il-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

