FROM amazonlinux

# Dependencies to build aws-lambda-cpp-runtime:
RUN yum -y install gcc-c++ libcurl-devel cmake3 jsoncpp-devel git make zip

# Dependencies to build sample code:
RUN yum -y install jsoncpp-devel