[package]
name = "sending-presinged-requests"
version = "0.1.0"
authors = ["Zelda Hessler <zhessler@amazon.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = {version = "1.5.9", features = ["behavior-version-latest"]}
aws-sdk-s3 = { version = "1.59.0", features = ["http-1x"] }
clap = { version = "4.5.20", features = ["derive"] }
hyper = { version = "1.5.0", features = ["client", "full"] }
hyper-tls = "0.6.0"
hyper-util = { version = "0.1.10", features = ["client-legacy", "tokio"] }
reqwest = "0.12.9"
tokio = { version = "1.41.0", features = ["full"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
