---
# Basic Amazon S3 bucket and object examples
files:
  - path: s3_basics/bucket_wrapper.py
    services:
      - s3
  - path: s3_basics/demo_bucket_basics.py
    services:
      - s3
  - path: s3_basics/object_wrapper.py
    services:
      - s3
  - path: s3_basics/presigned_url.py
    services:
      - s3
  - path: s3_basics/test/conftest.py
    services:
      - s3
  - path: s3_basics/test/test_bucket_wrapper.py
    services:
      - s3
  - path: s3_basics/test/test_demo_bucket_basics.py
    services:
      - s3
  - path: s3_basics/test/test_object_wrapper.py
    services:
      - s3
  - path: s3_basics/test/test_presigned_url.py
    services:
      - s3
...
---
# Amazon S3 file transfer demo
files:
  - path: file_transfer/demo_file_transfer.py
    services:
      - s3
  - path: file_transfer/file_transfer.py
    services:
      - s3
  - path: file_transfer/test/conftest.py
    services:
      - s3
  - path: file_transfer/test/test_file_transfer.py
    services:
      - s3
...
---
# Amazon S3 versioning demo
files:
  - path: s3_versioning/batch_versioning.py
    services:
      - iam
      - s3
      - s3control
      - sts
      - lambda
  - path: s3_versioning/remove_delete_marker.py
    services:
      - s3
      - lambda
  - path: s3_versioning/revise_stanza.py
    services:
      - s3
      - lambda
  - path: s3_versioning/versioning.py
    services:
      - s3
  - path: s3_versioning/test/conftest.py
    services:
      - s3
  - path: s3_versioning/test/test_batch_versioning.py
    services:
      - iam
      - s3
      - s3control
      - sts
      - lambda
  - path: s3_versioning/test/test_remove_delete_marker.py
    services:
      - s3
      - lambda
  - path: s3_versioning/test/test_revise_stanza.py
    services:
      - s3
      - lambda
  - path: s3_versioning/test/test_versioning.py
    services:
      - s3
...
