name: "Auto Labeler"

on:  # yamllint disable-line rule:truthy
  pull_request_target:
    branches:
      - main
jobs:
  auto-labeler:
    name: Auto Labeler
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # The Add Labels workflow adds a label to pull requests
      # based on the files included in the proposed change.
      #
      # To use this workflow, you must set up and configure 
      # rules in a .github/label-ruleset.yml file 
      #
      # For more information, see:
      # https://github.com/actions/labeler
      - name: Add Labels
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/label-ruleset.yml
