name: Lint Python

on:  # yamllint disable-line rule:truthy
  pull_request:
  workflow_dispatch:

jobs:
  linting:
    name: Linting & Formatting with autopep8, pyupgrade, black, isort, and flynt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: "**.py"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install autopep8 pyupgrade black isort flynt

      - name: Run autopep8, pyupgrade, black, isort, and flynt
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          changed_files=(${{steps.changed-files.outputs.all_changed_files}})
          
          # Run autopep8 with single aggressive mode on changed files
          autopep8 --in-place --aggressive "${changed_files[@]}"
          
          # Run pyupgrade to ensure Python 3.6+ compatibility only on changed files
          for file in "${changed_files[@]}"; do
            pyupgrade --py36-plus "$file"
          done
          
          # Run black for consistent formatting on changed files
          black "${changed_files[@]}"
          
          # Sort imports using isort on changed files
          isort "${changed_files[@]}"
          
          # Use flynt to convert string formatting to f-strings on changed files
          flynt "${changed_files[@]}"
