name: Lint Python

on:  # yamllint disable-line rule:truthy
  pull_request:
  workflow_dispatch:

jobs:
  black:
    name: Flake8 Linting & Ruff Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: "**.py"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install ruff flake8

      - name: Run Ruff & Flake8
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          changed_files=(${{steps.changed-files.outputs.all_changed_files}})
          ruff check "${changed_files[@]}"
          flake8 "${changed_files[@]}"
