name: Kotlin Linter

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:

jobs:
  ktlint:
    name: Lint Kotlin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@e9772d140489982e0e3704fea5ee93d536f1e275
        with:
          files: "kotlin/**/*.{kt,kts}"
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
      - name: Install ktlint via curl
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.3.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - name: Run ktlint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          ktlint --reporter=plain?group_by_file --editorconfig=".github/linters/ktlint_config"
        continue-on-error: false
