name: "Lint C++"
on:   # yamllint disable-line rule:truthy
  pull_request:
  workflow_dispatch:

jobs:
  cpplint:
    name: Lint CPP
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            cpp
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: "cpp/**/*.{cpp,h}"
      - name: "Run clang-tidy check"
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./.github/sd-cpp-linter
        with:
          config_file: ./.github/cpp-linter/clang-tidy-config.txt
          token: ${{ secrets.GITHUB_TOKEN }}
