name: Lint Yaml

on:  # yamllint disable-line rule:truthy
  pull_request:
  workflow_dispatch:

jobs:
  yamllint:
    name: Lint Yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            .doc_gen/metadata
            .tools
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: "**/*.{yml,yaml}"
      - name: Setup Python
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: >-
          python3 -m pip install -r .tools/base_requirements.txt
      - name: Lint YAML files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: >-
          yamllint --format standard -c .tools/validation/.yamllint.yaml .
